import type { ArticlePlots } from "@/types";

export const articlePlots: ArticlePlots = {
  plots: [
    {
      id: "jalyx-hunt-scatter-plot",
      type: "scatter",
      data: [
        { EPA: 0.02, Success_Rate: 0.42, name: "B.Wagner" },
        { EPA: 1.02, Success_Rate: 0.90, name: "D.Slay" },
        { EPA: -0.04, Success_Rate: 0.29, name: "E.Roberts" },
        { EPA: 0.41, Success_Rate: 0.57, name: "E.Murray" },
        { EPA: 1.05, Success_Rate: 0.92, name: "R.Douglas" },
        { EPA: -0.25, Success_Rate: 0.50, name: "M.Milano" },
        { EPA: -1.55, Success_Rate: 0.60, name: "A.Witherspoon" },
        { EPA: 1.61, Success_Rate: 1.00, name: "M.Lattimore" },
        { EPA: 0.09, Success_Rate: 0.45, name: "A.Anzalone" },
        { EPA: 0.17, Success_Rate: 0.60, name: "D.Elliott" },
        { EPA: -0.40, Success_Rate: 0.20, name: "F.Luvu" },
        { EPA: 0.89, Success_Rate: 0.78, name: "J.Reid" },
        { EPA: 0.86, Success_Rate: 0.71, name: "Ta.Johnson" },
        { EPA: -0.77, Success_Rate: 0.54, name: "O.Burks" },
        { EPA: 1.20, Success_Rate: 1.00, name: "M.Fitzpatrick" },
        { EPA: 0.02, Success_Rate: 0.40, name: "R.Smith" },
        { EPA: -0.23, Success_Rate: 0.40, name: "A.Al-Shaair" },
        { EPA: 0.96, Success_Rate: 0.60, name: "P.Locke" },
        { EPA: -0.11, Success_Rate: 0.38, name: "C.Gardner-Johnson" },
        { EPA: 0.61, Success_Rate: 0.80, name: "D.Tranquill" },
        { EPA: 0.58, Success_Rate: 0.60, name: "B.Cashman" },
        { EPA: 0.29, Success_Rate: 0.73, name: "C.Rozeboom" },
        { EPA: -0.00, Success_Rate: 0.40, name: "N.Madubuike" },
        { EPA: 0.65, Success_Rate: 1.00, name: "B.Jones" },
        { EPA: 1.82, Success_Rate: 1.00, name: "I.Rodgers" },
        { EPA: 0.39, Success_Rate: 0.67, name: "M.Harrison" },
        { EPA: 1.09, Success_Rate: 0.83, name: "N.Igbinoghene" },
        { EPA: 0.79, Success_Rate: 0.88, name: "J.Chinn" },
        { EPA: 0.25, Success_Rate: 0.67, name: "T.Dye" },
        { EPA: 0.72, Success_Rate: 0.71, name: "Z.Baun" },
        { EPA: 0.83, Success_Rate: 0.57, name: "A.Washington" },
        { EPA: -0.29, Success_Rate: 0.57, name: "N.Bolton" },
        { EPA: -0.44, Success_Rate: 0.71, name: "D.Hamlin" },
        { EPA: -0.58, Success_Rate: 0.14, name: "G.Rousseau" },
        { EPA: 0.87, Success_Rate: 0.82, name: "R.Blankenship" },
        { EPA: 1.10, Success_Rate: 1.00, name: "T.McDuffie" },
        { EPA: -1.27, Success_Rate: 0.00, name: "G.Karlaftis" },
        { EPA: 1.78, Success_Rate: 1.00, name: "B.Cook" },
        { EPA: 1.11, Success_Rate: 0.86, name: "D.Stingley" },
        { EPA: -0.13, Success_Rate: 0.60, name: "T.Bernard" },
        { EPA: 0.90, Success_Rate: 0.88, name: "C.Benford" },
        { EPA: 0.42, Success_Rate: 0.50, name: "K.Joseph" },
        { EPA: -0.22, Success_Rate: 0.22, name: "Q.Lake" },
        { EPA: 0.08, Success_Rate: 0.33, name: "K.Hamilton" },
        { EPA: 0.34, Success_Rate: 0.40, name: "R.Moss" },
        { EPA: 0.41, Success_Rate: 0.60, name: "D.Henley" },
        { EPA: -0.39, Success_Rate: 0.40, name: "Do.Williams" },
        { EPA: -0.16, Success_Rate: 0.29, name: "I.Pace" },
        { EPA: -0.06, Success_Rate: 0.38, name: "C.Conner" },
        { EPA: -1.69, Success_Rate: 0.14, name: "N.Smith" },
        { EPA: 0.92, Success_Rate: 0.75, name: "J.Campbell" },
        { EPA: -1.25, Success_Rate: 0.00, name: "W.Anderson" },
        { EPA: -1.17, Success_Rate: 0.14, name: "K.Turner" },
        { EPA: 0.28, Success_Rate: 0.38, name: "B.Branch" },
        { EPA: 0.82, Success_Rate: 0.86, name: "Q.Martin" },
        { EPA: 0.50, Success_Rate: 0.67, name: "J.Porter" },
        { EPA: -0.27, Success_Rate: 0.17, name: "J.Hunt" },
        { EPA: -0.07, Success_Rate: 0.57, name: "O.Speights" },
        { EPA: 1.39, Success_Rate: 1.00, name: "J.Hicks" },
        { EPA: 1.12, Success_Rate: 0.75, name: "K.Kinchens" },
        { EPA: 0.78, Success_Rate: 0.78, name: "C.DeJean" },
        { EPA: 0.44, Success_Rate: 0.80, name: "T.Smith" },
        { EPA: -1.20, Success_Rate: 0.00, name: "J.Verse" },
        { EPA: 1.27, Success_Rate: 0.80, name: "C.Bishop" },
        { EPA: 0.65, Success_Rate: 0.56, name: "Q.Mitchell" },
        { EPA: 1.18, Success_Rate: 0.88, name: "M.Sainristil" },
        { EPA: 0.49, Success_Rate: 0.60, name: "T.Arnold" }
      ],
      config: {
        xAxis: "EPA",
        yAxis: "Success_Rate",
        title: "Solo Tackle Success Rate",
        colorKey: "name"
      }
    },
    {
      id: "jalyx-hunt-line-plot",
      type: "stacked-line",
      data: [
        { Week_Number: 1, Percent_Team_Snaps: 0, RA_Percent: 0 },
        { Week_Number: 2, Percent_Team_Snaps: 0, RA_Percent: 0 },
        { Week_Number: 3, Percent_Team_Snaps: 0, RA_Percent: 0 },
        { Week_Number: 4, Percent_Team_Snaps: 0.06, RA_Percent: 0.015 },
        { Week_Number: 5, Percent_Team_Snaps: 0, RA_Percent: 0.015 },
        { Week_Number: 6, Percent_Team_Snaps: 0, RA_Percent: 0.015 },
        { Week_Number: 7, Percent_Team_Snaps: 0.16, RA_Percent: 0.055 },
        { Week_Number: 8, Percent_Team_Snaps: 0.05, RA_Percent: 0.0525 },
        { Week_Number: 9, Percent_Team_Snaps: 0, RA_Percent: 0.0525 },
        { Week_Number: 10, Percent_Team_Snaps: 0.42, RA_Percent: 0.1575 },
        { Week_Number: 11, Percent_Team_Snaps: 0, RA_Percent: 0.1175 },
        { Week_Number: 12, Percent_Team_Snaps: 0.38, RA_Percent: 0.2 },
        { Week_Number: 13, Percent_Team_Snaps: 0.49, RA_Percent: 0.3225 },
        { Week_Number: 14, Percent_Team_Snaps: 0.54, RA_Percent: 0.3525 },
        { Week_Number: 15, Percent_Team_Snaps: 0.4, RA_Percent: 0.4525 },
        { Week_Number: 16, Percent_Team_Snaps: 0.54, RA_Percent: 0.4925 },
        { Week_Number: 17, Percent_Team_Snaps: 0.59, RA_Percent: 0.5175 },
        { Week_Number: 18, Percent_Team_Snaps: 0.34, RA_Percent: 0.4675 },
        { Week_Number: 19, Percent_Team_Snaps: 0.32, RA_Percent: 0.4475 },
        { Week_Number: 20, Percent_Team_Snaps: 0.24, RA_Percent: 0.3725 },
        { Week_Number: 21, Percent_Team_Snaps: 0.53, RA_Percent: 0.3575 }
      ],
      config: {
        xAxis: "Week_Number",
        yAxis: "Percent Team Snaps",
        title: "Monthly Trend"
      }
    },
    {
      id: "jalyx-hunt-table",
      type: "table",
      data: [
        { Name: "G. Karlaftis", Success_Rate: "100%" },
        { Name: "W. Anderson", Success_Rate: "100%" },
        { Name: "J. Verse", Success_Rate: "100%" },
        { Name: "N. Smith", Success_Rate: "86%" },
        { Name: "K. Turner", Success_Rate: "86%" },
        { Name: "G. Rousseau", Success_Rate: "86%" },
        { Name: "J. Hunt", Success_Rate: "84%" },
        { Name: "F. Luvu", Success_Rate: "80%" },
        { Name: "Q. Lake", Success_Rate: "78%" },
        { Name: "I. Pace", Success_Rate: "71%" },
        { Name: "E. Roberts", Success_Rate: "71%" },
        { Name: "K. Hamilton", Success_Rate: "67%" }
      ],
      config: {
        xAxis: "Name",
        yAxis: "Success_Rate",
        title: "Success Rate per Player"
      }
    }
  ]
}; 